### ISSUE TITLE
Reverse Volume Reconstruction - Going from reconstructed US volume to 2D images

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#1005]
Is it possible to 'extract'/sample the 2D location-tagged ultrasound frames from a reconstructed US volume, given the reconstructed volume and the time-stamped ImageToReference transforms? Is this possible using Slicer/SlicerIGT? I understand that the sampled frames would not be the original resolution that US was captured in.

**Comment by ungi** [comment]
If your 3D reconstruction is in the Reference coordinate system, and you have a series of ImageToReference transforms, then you use the vtkImageReslice filter in Slicer's python interactor to obtain a cross section of the volume where Image would be. It should be possible to write a Python script that extracts the cross sections using a sequence of transforms. As you said, there will be loss of information due to resolution, compounding, tracking errors, etc. so it's not an ideal solution.
If you decide to use vtkImageReslice, here is an example code to get started: https://gist.github.com/ungi/80442ac03b5ea9ed6ae680a800837ece
