### ISSUE TITLE
Time sequence .mha file custom importer script

### ISSUE THREAD

**Issue by QianqianCai** [PlusToolkit/PlusLib#1079]
I am working on the temporal and spatial calibration of the tracked ultrasound imaging using the toolkit.

I found the following files imported to the example configuration file. And my goal is to create the two sequence data from the images in DICOM format and motion data in .csv format of my own experiment data.

- SequenceFile="WaterTankBottomTranslationTrackerBuffer-trimmed.igs.mha
- SequenceFile="WaterTankBottomTranslationVideoBuffer.igs.mha

Issue #645 mentioned about custom importer scripts in Python. Does anyone know where to download some example script? 

Thank you!

**Comment by adamrankin** [comment]
This is a common issue, but because there are so many potential input file formats, we do not provide an implementation.

I recommend you look at the format of your source data, and the format of the target data, and either write a python script to generate it, or another set of tools to convert (sometimes I use notepad++ with regex to generate the transform header data, sometimes I use excel to help generate lists of numbers, there are so many ways to do it).
