### ISSUE TITLE
Config file location depends on Visual Studio/Windows launch

### ISSUE THREAD

**Issue by adamrankin** [PlusToolkit/PlusLib#184]
When PlusServer is launched from visual studio (in debug, haven't tested release) ndi tool definitions are loaded as 
`RomFile="NdiToolDefinitions/8700248.rom"`

When launched from PlusServerLauncher, ndi tool definitions must be loaded as 
`RomFile="../NdiToolDefinitions/8700248.rom"`

**Comment by lassoan** [comment]
Location of configuration data files are specified relative to the Plus configuration file location. So, it should not matter what is the working directory. Maybe RomFile location is not properly determined using PlusConfig but the relative path is passed to ndicapi?

**Comment by adamrankin** [comment]
Location of config files is set to absolute path relative to cloned folder ${PLUS_PLUSLIBDATA_DIR} in build configuration, not sure about installed package configuration.

Regardless, DeviceSetConfigurationDirectory is changed when a new config file folder is selected via PlusServerLauncher.

`  DeviceSetConfigurationDirectory="C:/d/PB-x86/PlusLibData/ConfigFiles/Robarts"`

This makes the Ndi tools loaded relative to the loaded config file.

**Comment by adamrankin** [comment]
Perhaps we should have a separate "Data" folder which can hold Markers, NdiToolDefinitions, etc... everything that isn't actually a config file.

**Comment by lassoan** [comment]
Data files that are referenced in a config file should be specified relative to the actual config file location (does not matter what the config files directory setting is). Is this the behavior that you see? If not then it's a bug.

**Comment by adamrankin** [comment]
Ah, no this is not the behaviour. Files are referenced relative to the DeviceSetConfigurationDirectory from the PlusConfig.xml

This is assumed to be the same as there is usually a GUI that sets them in parallel, but when launching from Visual Studio, that is not the case.

**Comment by lassoan** [comment]
OK. I've checked the code and found that vtkPlusConfig::FindImagePath and vtkPlusConfig::FindModelPath searches for files relative to the device set configuration file (and later they look into image and model directories and DeviceSetConfigurationDirectory).

When a device looks for calibration files, tool files, etc. then a similar function should be used. Maybe it could be called vtkPlusConfig::FindConfigDataPath or something like that.

Overall, I don't think our folder structure (config, model, image, data) makes much sense now. It was not very clear earlier either and it has become just more blurry over time. We should revise it now.

Some considerations:
- It would be better to keep config files closer to source files. PlusLibData is now a separate repository, so source and config file examples can get out of sync more easily.
- Images, models, and additional files that device set config files use are not really different from each other. Maybe we could put them all into one folder.
- We should keep large files (long sequences, maybe also large models) in PlusLibData to reduce repository size (and maybe later we can set up git-lfs or CMake ExternalData for managing PlusLibData).

What do you think about this?
- move config files and small additional files (calibration files, small models, etc.) into PlusLib
- move all large files into PlusLibData\TestData (any better suggestion than TestData? it is not strictly test data)

**Comment by adamrankin** [comment]
I was going to work on this today, do you want it in before or after release?

**Comment by lassoan** [comment]
Maybe the best would be to implement this on a separate branch (Plus-2.7) to avoid the chance of regressions.

**Comment by lassoan** [comment]
As a second thought... it would be better to have similar directory structure for both the stable and master version. It would make it easier to backport patches, etc. We'll have to be careful and thoroughly test things.

**Comment by adamrankin** [comment]
I don't know how I feel about separating files by size. I know that's a practical consideration, but it seems unwieldy from an organizational perspective.

I'd keep files arranged by type (image/model/config/data folders). Keep PlusLibData (rename to just PlusData?) 

What I think does need to happen is that all data files are stored relative to the parent data folder (as it is now), and the code always looks relative to the data folder (right now, code looks relative to config file). Config files with unique needs could specify absolute paths for non-standard setups.

Perhaps we could consolidate the source code to just vtkPlusConfig::FindDataFile(requestedFileName) and it intelligently searches all subfolders?

**Comment by lassoan** [comment]
What to implement in the source code is quite clear: have a generic FindDataFile method that looks at many places. Current behavior is almost correct, it should start relative to the config file (that way we can always relocate the config file and all related data files anywhere, we just have to move them together), then predefined directories, current working directory, executable's directory, etc. Recursive search in all subfolders is very risky - you may end up globbing large directories for a long time, which users would interpret as "Plus crashed".

The big question is what to do with data.

> I don't know how I feel about separating files by size

I feel bad, too, but unfortunately, simply because a file is big, we must treat it differently. Options:
- Option A: separate git repository for large files: helps keeping the code repository small, download can be optional, but difficult to decide what to move to a separate repository.
- Option B: Make external data infrastructure: no need to set up any additional tool (CMake supports this) but need to set up and maintain our own server, with our own account management, and uploading a file is not a trivial process
- Option C: git-lfs: everything can go into one git repository, but requires installation of additional tool, storage is opaque, if something goes wrong then it may be very difficult to solve, small extra cost

Maybe we could try to make Option A (current option) work and maybe also try how well Option B works out for us.

**Comment by adamrankin** [comment]
My comprehensive date has been set. Let's push this back until after release. It's not game breaking as the installed package works when operating under "normal" conditions.
