### ISSUE TITLE
PlusServer crashes when querying image list from StealthLink

### ISSUE THREAD

**Issue by lassoan** [PlusToolkit/PlusLib#249]
When OpenIGTLinkRemote module is used in Slicer to query list of available images from StealthLink through Plus, PlusServer crashes.

**Comment by Sunderlandkyl** [comment]
PlusServer shouldn't crash anymore when trying to query the image list or retrieve an image from StealthLink, however it still won't be functional until the openigtlink/OpenIGTLink#152 pull request is integrated.

**Comment by Sunderlandkyl** [comment]
I may have spoken too soon. I was testing the StealthLink with a different dataset when it crashed while attempting to download the selected image.

Debugging now.

**Comment by Sunderlandkyl** [comment]
I discovered that it was some sort of memory allocation issue in [vtkPlusStealthLinkTracker.cxx(669-670)](https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/StealthLink/vtkPlusStealthLinkTracker.cxx#L669-L670).
The server was crashing when trying to allocate ~223MB for the image data.

It was reproducible on a particular dataset for a while, unfortunately I am also not able to replicate the crash anymore.

It seems as though the issue resolved itself. Maybe it was caused by memory issues on my computer.

**Comment by lassoan** [comment]
In a 32-bit application the usable memory space is quite limited. Allocating large contiguous memory block can be particularly problematic. Memory usage of PlusServer can be reduced by limiting size of image buffers (if there is any acquisition device). Also, we could enable ReleaseDataFlag (https://www.vtk.org/Wiki/VTK/FAQ#Using_ReleaseDataFlag) on the VTK filters that process the received image and/or instead of creating a pipeline, we would run filters manually (call Update(), GetOutput(), delete the producing filter).

**Comment by Sunderlandkyl** [comment]
In order to reproduce the issue, I moved from the ~223MB CT to a ~523MB CT.
I haven't managed to fix it yet.

That has me wondering, at what point should we consider a dataset to be too large to support?

**Comment by lassoan** [comment]
Theoretical maximum memory space available for a 32-bit process is 2GB. Practically it usually means that you have about 1GB for data. Allocating contiguous memory blocks may easily fail, even if you have enough memory, just not in one piece. I would say that if we can deal with CTs up to 512^3, 16 bits then it is enough. We should not crash, though, but report an error and keep running.

**Comment by Sunderlandkyl** [comment]
This issue should now be fixed.
