### ISSUE TITLE
Streaming video from a MacBook webcam using OpenCV

### ISSUE THREAD

**Issue by leb** [PlusToolkit/PlusLib#312]
I just tried to make the optical marker tracker work with my MacBook by using an OpenCVVideo capture device instead of the MmfVideo device that is used in the example device set. However, in order to make the cv::VideoCapture connect to the webcam, I had to use a constructor without any video URL argument, i.e. I changed line 91 of [vtkPlusOpenCVCaptureVideoSource.cxx](https://github.com/PlusToolkit/PlusLib/blob/master/src/PlusDataCollection/OpenCVVideo/vtkPlusOpenCVCaptureVideoSource.cxx) from 

`this->Capture = std::make_shared<cv::VideoCapture>(this->VideoURL, this->RequestedCaptureAPI);`

to

`this->Capture = std::make_shared<cv::VideoCapture>(this->RequestedCaptureAPI);`

Would it be possible to make the VideoURL setting of the OpenCVVideo device optional, do you think?

**Comment by lassoan** [comment]
Does it work if you specify empty string for video url?

**Comment by jamesobutler** [comment]
I have actually thought about this as well. From the PLUS [mfVideoCaptureLibrary](https://github.com/PlusToolkit/PlusLib/tree/master/src/Utilities/MfVideoCaptureLibrary) under utilities the original work is stated in the header and from [here](https://github.com/PlusToolkit/PlusLib/blob/master/src/Utilities/MfVideoCaptureLibrary/MediaFoundationVideoCaptureApi.cpp#L9-#L13). From reading the articles and comments by that guy supposedly the implementation got adopted into opencv as well. So they might be very similar or maybe maintained a little more over there, not sure.

**Comment by leb** [comment]
It does not work with an empty string, no.

**Comment by lassoan** [comment]
I've checked the API in OpenCV. If you only specify an int argument in the constructor then the number specifies the capture device index.

```
VideoCapture::VideoCapture(const String& filename, int apiPreference)
{
    open(filename, apiPreference);
}

VideoCapture::VideoCapture(int index)
{
    open(index);
}
```

Therefore, I see two potential solutions:

1. Figure out what filename you have to use for cameras and other imaging devices on MacOSX. No code change is needed, just search on the web.

2. Allow using device index to connect to a camera. For this, we need to introduce a new "CaptureDeviceId" attribute in the XML file, the same way as it is done in [MMF video source](http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceMicrosoftMediaFoundation.html). If CaptureDeviceId is specified then you would use VideoCapture::VideoCapture(int index), otherwise you would use VideoCapture::VideoCapture(const String& filename, int apiPreference).

**Comment by leb** [comment]
We tried finding such a filename before we changed the code, but is doesn't seem to exist in macOS. We haven't been abel to find it, at least, and there are some posts around indicating that this is not the way to do it, so I believe solution 2. is the way to go.
