### ISSUE TITLE
Extracting transforms from Stealthstation (using StealthLink)

### ISSUE THREAD

**Issue by remidel** [PlusToolkit/PlusLib#330]
Hello,

I am using Slicer to visualize my neuro-navigation data from the Medtronic Stealthstation using StealthLink. However, I have to perform fiducial registration and pivot calibration in Slicer every time so that I can visualize my stylus according to my 3D phantom.

I am wondering if I can extract the ReferenceToRas transform (obtained with fiducial registration) and the stylusTipToStylus transform (obtained with pivot calibration) directly from the StealthStation. This would make the all process easier and faster since we already have to perform registration with the StealthStation.

I try to add the "ReferenceToRas" transform in the config file but It's not working. I am not able to visualize the stylus if I modify the transform hierarchy.

Thank you for your help.

Rémi Delaunay

**Comment by lassoan** [comment]
Retrieving patient registration is a very important feature of StealthLink support in Plus. There are some known limitations, though. What StealthStation application do you use? Which version?

@Sunderlandkyl will help you with the details.

**Comment by remidel** [comment]
I am using the version 2.1. I can retrieve patient registration and visualize the images in 3D Slicer but I don't have the position of my stylus relative to the Ras coordinate system (i.e. my phantom). I only have the position of the stylus relative to the reference (i.e. Small Passive Cranial Frame). 

I am using the SureTrack2 tool from medtronic that I am attaching to a custom probe. I am performing calibration of the tool on the StealthStation but I need to do the calibration (i.e. pivot calibration) again on slicer because the distance between the probe tip and the SureTrack is incorrect.

Thank you

**Comment by Sunderlandkyl** [comment]
In order to retrieve the ReferenceToRas transform, you'll need to download the image from StealthLink using OpenIGTLink Remote.

One the image is downloaded, Plus should start sending the ReferenceToRas transform.

**Comment by FaizanSiddiqui91** [comment]
Please guide me on how to download the image from StealthLink using OpenIGTLink Remote.

I am trying to get this by using the following command:

PlusServerRemoteControl.exe --command=GET_EXAM_DATA --device=SLD --dicom-directory="C:\StealthLinkDicomOutput" --volumeEmbeddedTransformToFrame="Ras" --keepReceivedDicomFiles

However, I am getting this response from the server:

Command ID: 1692268493
Status: FAIL
Error:
Message: vtkPlusStealthLinkCommand::Execute: failed, failed to receive image

The tracking works fine. The problem is just with the image data. Do I need to do anything else as well?
