### ISSUE TITLE
Accessing .mha sequence in Slicer after recording

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#513]
Is there a way to directly access .mha files in Slicer after recording with PlusRemote (the SlicerIGT module), without manually loading them? 
My intended workflow is: 
1) record freehand tracked US with Plus Remote 
2) perform image processing on the recorded US sequence in Slicer
3) Volume reconstruction on processed sequence using Plus Remote ('Offline Reconstruction').

**Comment by ungi** [comment]
Your intended workflow is easier if you record the ultrasound sequences directly in Slicer, using the Sequence Browser module (install Sequences extension).

**Comment by prash-p** [comment]
@ungi What is the correct way to record a image + transform sequence in the Sequence Browser? I tried recording but I get a lot of static ultrasound frames during playback, even with the playback framerate adjusted.

**Comment by prash-p** [comment]
What I am doing right now:
1. Connect to PLUS server using OpenIGTLink
2. Stream Image_Reference (Image in tracker reference frame) and reslice based on transforms using volume reslice driver
3. Sequence module  --> Create new sequence and add Image_Reference as a node
4. Sequence Browser module --> Add created sequence into the synchronized nodes box.
5. Check the record box and select Image_Reference as a proxy node.
6. Record data.
7. During playback of the recorded data, there is conflict between the data being streamed with PLUS and the sequence playback (which is what appeared as 'static ultrasound frames').
8. To avoid this I check 'Rename' in the synchronized nodes which creates a new volume which I can playback without the PLUS stream conflicting with it.

My issues and questions: 
The sequence playback/recording framerate is very slow even though I have selected 30 fps/120fps.
After processing the recorded image sequence, what is the best way to reconstruct it into a volume (is there a better way than saving it as a .mha and then manually selecting it in the PlusRemote module)?

Thanks!

**Comment by ungi** [comment]
You have a lot of information in one message...

Don't record Image_Reference, because transformations (Image->Reference) cannot be saved in image sequences. When you replay recorded Image_Reference, the tracking information will be lost. Change your PLUS config file to send Image_Image to Slicer, along with an ImageToReference transform. Record those two in Slicer Sequences.

Live streaming and replaying recorded sequences compete with each other and create flickering images. You need to pause one while playing the other. This is not a bug. Sequences and OpenIGTLinkIF work in similar ways. They update a "proxy node" that is a current representation of an instance of a time sequence.

There is currently no volume reconstructor in Slicer. It is an inconvenience, and it has historical reasons. You need to reconstruct a volume in PLUS using Plus Remote. You can also record the tracked ultrasound at the same time in Sequences. So eventually, you can save a scene with both reconstructed volume and 2D sequence. But if you only have a 2D sequence, it is a bit of manual labor to export and feed it into the offline VolumeReconstructor executable of the PLUS package.

**Comment by lassoan** [comment]
We are moving questions and discussions from the issue tracker to https://github.com/PlusToolkit/PlusLib/discussions. If you have remaining questions related to this topic, create a new discussion there. Thank you!
