### ISSUE TITLE
units of pose data

### ISSUE THREAD

**Issue by zhaobingshuai** [PlusToolkit/PlusLib#566]
Hey, when I use the volume reconstruction command line of plus, I want to know what the units of my pose data are.
Location: centimeter or meter?
Timestamp: milliseconds or seconds?
Thank you. I hope to get your help.

**Comment by ungi** [comment]
That is a really good question! The pose data is stored as transformation between two coordinate systems. The units of those coordinate systems are provided by the hardware manufacturer, or defined by the user. PLUS does not change that. Most tracker manufacturers use millimeters as unit. If the pose transformation matrices don't have a scaling component (the norms of the first three columns are 1.0), then the pose remains in millimeters. If the scaling is not 1.0, then it changes. E.g. in tracked ultrasound the scaling of the matrix is about 0.1, because one pixel is 0.1 millimeters. I hope this helps.

**Comment by zhaobingshuai** [comment]
@ungi 
thank you. It’s helpful for me.
