### ISSUE TITLE
PlusApp version 2.8 (stable) and 2.9 (latest build) do not work in Windows 7

### ISSUE THREAD

**Issue by AlexDorobantiu** [PlusToolkit/PlusLib#587]
PlusApp (versions 2.8 and 2.9) do not start and do not give any error message on windows 7. We (@carlos-luque, and @gvsocorro, and @AlexDorobantiu) ran the application using Plus Server Launcher. No window is open.

Version 2.6 (which we had as backup, but we cannot find a download link for) works.

**Comment by carlos-luque** [comment]
We did not have any error messages and the MSVC resdistutables were installed. Also, we tried to run the Plus Server launcher in windows command (cmd) and any windows are showed.  Could you recommend some command line or other thing to have more information in order to find the issue?

**Comment by AlexDorobantiu** [comment]
Thank you for the fast reply.
I installed back the version 2.8 in parallel with 2.6. (2.8 still doesn't work)

This is the output from the console when running Server Launcher and Version:

C:\Users\Alex\PlusApp-2.8.0.20190617-Win64\bin>PlusServerLauncher.exe

C:\Users\Alex\PlusApp-2.8.0.20190617-Win64\bin>PlusVersion.exe
System start timestamp: 12007
Software version: Plus-2.8.0.283830c3 - Win64

**Comment by AlexDorobantiu** [comment]
The application gives no error message at all when I try to run it. It shows for a brief moment in task manager and then closes. My colleagues succesfully ran the 2.8 version in Windows 10.

I will also add the log which is created after running the app. We cannot find any useful error in the log.
[082819_182645_PlusLog.txt](https://github.com/PlusToolkit/PlusLib/files/3551659/082819_182645_PlusLog.txt)

**Comment by AlexDorobantiu** [comment]
@lassoan  Thank you.
My computer is around 6 or more years old, with the videocard Nvidia GTX 770M. I did not change the OS because of some of the software previously installed which would have lost compatibility.
I will close this issue, but I ask, if it's possible, to add a minimum requirement of the OpenGL and/or of the OS for the new versions, since from the download webpage it seems like it should run on Windows 7 too. And if you read closer to the bottom of the page, maybe even XP SP 3.

**Comment by AlexDorobantiu** [comment]
![image](https://user-images.githubusercontent.com/19750597/63872616-b0e4c100-c9c6-11e9-8b72-067ba69e255f.png)

**Comment by AlexDorobantiu** [comment]
@Adam: yes, I have OpenGL 4.6 up and running

**Comment by AlexDorobantiu** [comment]
https://plustoolkit.github.io/download.html
This is the webpage where I read the list of compatible operating systems.

**Comment by lassoan** [comment]
Unfortunately, OpenGL version is not the full story. There are incompatibilities in old chipsets that are not supported with recent VTK and Qt versions. However, console applications, such as PlusVersion and PlusServer should have less issues, so if they fail then there may be some other problems.

You may also try run PlusVersion or PlusServer with --verbose=5 to get some more details; or run them from a debugger to get a call stack; or even better, build Plus in debug mode and run it in the debugger to see where and why it crashes.

**Comment by AlexDorobantiu** [comment]
I managed to run the version 2.8 using this command line:
C:\Users\Alex\PlusApp-2.8.0.20190617-Win64\bin>PlusServer.exe --config-file="../config/PlusDeviceSet_Server_MmfColorVideoCapture.xml" --verbose=5

This means that the server works without the user interface. When I try to run the launcher, the server does not start.

I ran PlusServerLauncher.exe --help and a window with the command line arguments opened.

**Comment by adamrankin** [comment]
I think our lab has one Windows 7 computer remaining, I'll see if I can replicate a setup. Note: it will take some time as I have quite a few other tasks on my plate at the moment, sorry.

**Comment by AlexDorobantiu** [comment]
There is no rush, I am using for now the version 2.6 which works out of the box. Thank you.

**Comment by jamesobutler** [comment]
Hi All (@AlexDorobantiu, @Sunderlandkyl, @adamrankin, @lassoan), 
I've completed some testing for this issue. Here is a report:

**Hardware used to test:**
Windows 7 workstation laptop (i7-2720QM, 6GB RAM, Quadro 2000M GPU)

**Replicating issue with Plus-2.8 Stable:**
I installed Plus-2.8 Stable (PlusApp-2.8.0.20190617-Win32) from the website download and was unable to get anything to run successfully. Below is an image of a crash report upon trying to run PlusVersion.exe.
![plus-version-crash](https://user-images.githubusercontent.com/15837524/64927998-267ec880-d7e0-11e9-9323-ac4b259b007e.png)
**Replicating issue with Plus-2.9:**
I then installed Plus-2.9 (PlusApp-2.9.0.20190913-Win32) from the website download and had the same problems.  Plus-2.9 might have simply not started due to the issue reported in https://github.com/PlusToolkit/PlusLib/issues/594 which was fixed. Unclear how long Plus-2.9 downloaded from the website had simply not worked.
**Building Plus-2.8 Stable in debug mode:**
I then built Plus-2.8 in debug mode with just the mmf webcam device specified to build.  I ran PlusVersion.exe and PlusServerLauncher.exe and had no issues. Device support was reported from PlusVersion and I started a server for the mmf device with PlusServerLauncher successfully.
**Looking into other supported devices as source of errors:**
I then looked into what other devices are built with the Plus packages that I downloaded from the website.  The device that I believe is causing problems for Windows 7 installs is the **IntelRealSense** device.  I was able to determine that the realsense2.dll that is included with Plus-2.8 and in Plus-2.9 is the dll downloaded from the official install of [Intel Realsense SDK 2.0 (build 2.23.0)](https://github.com/IntelRealSense/librealsense/releases/tag/v2.23.0). However, the problem is that there is a Windows 7 version and a Windows 10 version. The Windows 10 version (Intel.RealSense.SDK-WIN10-2.23.0.909.exe) is being used for the Plus packages, however this doesn't work for Windows 7. You can read about the support for Windows 7 where the binaries are different from Windows 10 in the following intel realsense [document](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_win7.md).

**Temp Solution:**
If you copy the Win7 appropriate realsense2.dll (C:\Program Files (x86)\Intel RealSense SDK 2.0 (Win7)\bin\x86\realsense2.dll) into the PlusApp-2.8.0.20190617-Win32/bin to replace the Win10 realsense.dll, PlusVersion.exe and PlusServerLauncher starts working again and it won't have the crash dialog show up.

**Options for real solution:**
1. Remove IntelRealSense support from the standard Plus-2.8/2.9 packages and create new special packages that specifically includes IntelRealSense for Windows 10 (32 and 64 bit support) and another for Windows 7 (32 and 64 bit support).
2. Keep IntelRealSense support in the standard Plus-2.8/2.9 packages, but create Windows 7 and Windows 10 versions. (Win7 x32, Win7 x64, Win10 x32, Win10 x64)
3. Drop Windows 7 support for the standard Plus-2.8/2.9 packages downloaded from the website while making sure that the documentation/text on the pages is updated to reflect this dropped support. Windows 7 is currently in "extended support", but Microsoft has current plans to mark it EOL on January 14th, 2020 ([source](https://www.microsoft.com/en-us/microsoft-365/windows/end-of-windows-7-support)). This means in less than 4 months Windows 7 will no longer be receiving any security updates.  Continuing to support an OS that will soon no longer receive security updates for the main Plus packages (standard win32 and win64 packages) is something that should be considered.

**Comment by adamrankin** [comment]
My vote is 3.

**Comment by lassoan** [comment]
Thanks for the investigation, it is very useful.

We maintain a Windows XP embedded build (to support Ascension trackers on Ultrasonix systems). These should be usable on Windows7, too. Would these work for you?

If yes, then we would just need to change the download page to clarify exactly which releases can be used with Windows 7 and XP.

**Comment by jamesobutler** [comment]
@carlos-luque, and @gvsocorro, and @AlexDorobantiu,

Could you provide information about which Plus devices you are trying to run on your Windows 7 machine? From one of the previous posts you attempted to run a mmf device on the Windows 7 machine, but not sure if that was just part of testing or if that’s the device you actually want to run on Windows 7.

It looks like the Stealthlink package is the only one that doesn’t include IntelRealSense while also having mmf video device support.

**Comment by AlexDorobantiu** [comment]
We are trying to run the DeviceOpticalMarkerTracker, from the tutorial available here:
http://perk-software.cs.queensu.ca/plus/doc/nightly/user/DeviceOpticalMarkerTracker.html

**Comment by jamesobutler** [comment]
@Sunderlandkyl @lassoan There doesn’t appear to be any current Plus package that can be downloaded that will work for them. For Windows 7, they need a package that has OpticalMarkerTracker, mmf and no IntelRealSense. It appears that OpticalMarkerTracker documentation shows you can use an mmf or a realsense device. As a cheaper tracking solution it is likely that others will also have older systems running Windows 7.
