### ISSUE TITLE
Intended usage of Sensor Holder part?

### ISSUE THREAD

**Issue by prash-p** [PlusToolkit/PlusLib#600]
Hi, I'm designing a tracking fixture part for a surgical drill, and I'm trying to use as many of the parts from https://github.com/PlusToolkit/PlusModelCatalog/tree/master/TrackingFixtures instead of designing from scratch. 

I'm a bit confused about what the 'Sensor Holder' part is supposed to be used with? Is it supposed to have a cylinder fit through the space, and if so, what diameter works best? Or is it for another custom part?

**Comment by adamrankin** [comment]
I think that's for the Ascension magnetic tracker sensors.

**Comment by lassoan** [comment]
There are also various tools that have shaft that snap into the same 8x8mm rectangular prism shaped slot.

Recently, we have been moving away from this snap-in assembly because the snap-in mechanism is relatively large, not easy to print without support material, and not very rigid. We are also moving towards using flat markers, which are faster and cheaper to print and also lighter.

We are also moving away from SolidWorks due to hassles with licensing and use Autodesk Fusion 360 instead.

@ungi Could you share some links to models of latest tracking fixture designs?

**Comment by ungi** [comment]
Hi Prash,

We have been using the built-in repository that comes with Fusion 360 in the past few years. There is no easy way to share the entire repository in the public. At least not that I know of. Since we collaborate with each other, I'm happy to send you a private invitation to the entire Perk Lab repository. Just send me your Fusion 360 username.
Note that Fusion 360 is free for all students, teachers, and small companies. In my opinion it's much easier to use than SolidWorks, and can be learned in a few days.

Tamas

**Comment by prash-p** [comment]
Hi all, 

Thanks a lot for the answers. Tamas, that's very kind of you - I'll send you an email with my Fusion 360 username once I've set it up - thanks!
