### ISSUE TITLE
Landmark Registration: ArUco Markers & Laptops

### ISSUE THREAD

**Issue by jennyrhodes** [PlusToolkit/PlusLib#646]
Hi again. 

I have had significant issues with Landmark Registration and ArUco markers. I was finally able to get it to work after much trial/error.

The biggest issue seems to be the connection to the plus server (and potentially my internet connection...even though I hard-wired into the ethernet) and/or the laptop I am using.

I moved to a desktop computer and most of my problems were solved.

However, we would eventually like to use the ArUco Markers with webcam tracking on a laptop for travel. 

**Is there a laptop that you would recommend for this purpose?** We have been using a Surfacebook and it is an absolute nightmare.

**Comment by jennyrhodes** [comment]
I think the big issue is despite going through the tutorials for landmark registration, I am still having issues understanding the process. Is there a step-by-step video available just showing how to do landmark registration on a square or very simple model?

**Comment by markasselin** [comment]
Hi Jenny,

Thanks for your question. We have used OpticalMarkerTracking (ArUco) on many different laptops in the past, but below I have listed some suggestions which from my experience may help improve your experience.

- Use an external webcam to have more flexibility to position the camera adequately to see the markers
- RAM shouldn't really be a limiting factor here (unless you want to use 4k video, even then 4GB should be sufficient) but having a faster CPU will increase the ArUco processing speed
- Ensure autofocus is disabled on any camera you choose to use

If you're running PLUS on the same machine as Slicer then your ethernet speed shouldn't influence the PLUS connection (since the connection will be over localhost). For some unknown reason SurfaceBook machines don't seem to play well with the OpticalMarkerTracker device, but every other computer we have tried seems to be just fine. Maybe try a different laptop and see if the issues persist?

Hope this helps,
--Mark
