### ISSUE TITLE
Unable to obtain ultrasound data even though it's connected

### ISSUE THREAD

**Issue by eibhinwhite** [PlusToolkit/PlusLib#652]
Hi,
I am currently trying to load live ultrasound data from an Ultrasonix machine to Slicer on another laptop. I am using the 'Ultrasonix ultrasound imaging device' which is already uploaded on Plus App win32, however changing the IP address to suit mine. I am getting a black screen although the connection was successful, however the red circle states that no data is available. I'll insert a screengrab of this. Any help would be greatly appreciated, thanks. 
![image](https://user-images.githubusercontent.com/57176240/73255631-61deca00-41b8-11ea-9ced-01fa28ccca6b.png)

**Comment by lassoan** [comment]
Which Plus version do you use? What is the exam software version on your Ultrasonix machine?

**Comment by eibhinwhite** [comment]
The plus version is the Ultrasonix 5.7 version and the exam software on the
Ultrasonix is Sonix RP. Thank you.

**Comment by lassoan** [comment]
Sonix RP is the hardware model name. You can install many different versions of Exam software on this hardware. What is the version of your Exam software? If you use Plus release with Ultrasonix 5.7 then the Exam software version should be the same, otherwise you get those communication errors that showed up in your log file.
