### ISSUE TITLE
information about camera device

### ISSUE THREAD

**Issue by fcenni** [PlusToolkit/PlusLib#690]
Hi all,
I am a new user for PLUS toolkit and I am interested in using motion tracking system from Qualysis.
https://www.qualisys.com/?gclid=CjwKCAjw2a32BRBXEiwAUcugiJo1SigO1uUDeIyvs2xLa-WJ-pHK4YbUExywD5459exDDRUERa6jnRoC5r8QAvD_BwE
I was wondering, are there already available API for this device?

Kind regards
Francesco

**Comment by lassoan** [comment]
Qualisys systems are unreasonably expensive for image-guided therapy, because their advanced software features are not used and the hardware capabilities alone do not justify the high price tag. 

Therefore, for most applications it is cheaper to buy a complete new OptiTrack system for a few thousand dollars than implement an interface class for Qualisys. For example, an [Optitrack Duo](https://www.optitrack.com/products/v120-duo/) costs $2300 (and there are inexpensive multi-camer options, too).

If you are willing to spend 1-2 weeks with implementing an interface for Qualisys device then let us know, we would be happy to give you advice.

**Comment by fcenni** [comment]
Thanks for your reply. That's completely understandable. My idea is to combine gait analysis (qualysis is commonly used) with US systems (telemed). Qualysis provides a large field of view thus suitable for captured skin markers during gait. 
I read that QTM (qualysis) uses TCP/IP connection. I was wondering, is it possible to stream data to PLUS using this connection (via OpenIGTLink?), in real-time or using virtual capture? 
I am naive to stream protocol and I am searching possible solutions to use Qualysis. Thanks

**Comment by Sunderlandkyl** [comment]
I think that Qualysis uses their own communication protocol, so it would require a new device.

Qualysis also has a C++ api, so support could be added with the creation of a few classes in Plus that could retrieve the data directly https://www.qualisys.com/software/real-time-sdk/.

If you're interested in implementing an interface for this device, then you can find more information on the process here: https://plustoolkit.github.io/devicecode
