### ISSUE TITLE
Can I connect the fiagon with plus?

### ISSUE THREAD

**Issue by timeanddoctor** [PlusToolkit/PlusLib#763]
This is Fiagon web: https://www.fiagon.com/ous/

**Comment by ungi** [comment]
As far as I can tell from the photos, they use NDI Aurora electromagnetic tracking. That device is supported in PLUS. But I'm not sure if Fiagon has done anything to hide the interface (both physical and software) from regular users. If you want to use the device while the Fiagon is software is running at the same time, then you need to ask Fiagon if they provide an output. Something like a research interface. Because NDI does not broadcast its tracking data to multiple devices directly.

**Comment by adamrankin** [comment]
Ty @ungi
