### ISSUE TITLE
XML file for 'Ephiphan' and 'NDI Aurora'

### ISSUE THREAD

**Issue by yogeren** [PlusToolkit/PlusLib#799]
I am trying to use PLUS Toolkit to grab information from an ultrasound machine (using the ephiphan video to get the image from the display monitor) and an Ascension 3DG. And then use the fCal to to do the calibration.

But I have some trouble with the xml file. Is there any xml file adapted to the 'Ephiphan' and 'Ascension 3DG'?

Any guidance would be much appreciated
Thanks

**Comment by ungi** [comment]
The example config files are here: https://github.com/PlusToolkit/PlusLibData/tree/master/ConfigFiles
You can copy-paste two different devices from two example config files in your config file to combine them.
I only recommend fCal if you want to develop and automated calibration system and you have lots of patience and resources. Otherwise, U-31 on this page is a better way to calibrate a tracked ultrasound: http://www.slicerigt.org/wp/user-tutorial/
