### ISSUE TITLE
Install / Windows Setup: Configuration File name

### ISSUE THREAD

**Issue by msimonc** [PlusToolkit/PlusLib#800]
My ...\PlusApp..Win64\config folder contains several .xml files,

How do I specify which one to use?

**Comment by ungi** [comment]
When you run the PlusServerLauncher application, you can select the folder that holds your config file. The lower combo box will be populated using every valid config file. You can select and launch any of them. But it is rare that one example config file is just what you need. They typical use is to copy-paste sections for devices from a config file and compile a config file that represents your specific hardware setup.

Recently, config files can be sent to PlusServerLauncher from Slicer using the Plus Remote module (after installing SlicerIGSIO extension). That is more convenient, because you can control PLUS from Slicer and don't need to switch between applications.

**Comment by msimonc** [comment]
As the Plus Remote module is not found in Extension Manager,
should I install it with Extension Wizard?  Thanks,

**Comment by ungi** [comment]
The Plus Remote module is bundled in the SlicerOpenIGTLink extension, not SlicerIGSIO. Sorry for the confusion. Use Extension Manager to install extensions.
Unfortunately we don't have tutorials for these new modules. But you can load a config file in Slicer as a "Text file". Note that when you drag and drop an XML file on Slicer, it will offer to load it by default as a Slicer scene, so you need to pick Text file there manually.
When that text file is loaded, you can start PlusServerLauncher on your computer, go to Plus Remote module, create a new Launcher node, Add a server, and select the loaded text file in the "Config file" section.
It's a bit complicated and you may want to first test if you can run your config file without errors in PlusServerLauncher.

**Comment by ungi** [comment]
I just realized we used Plus Remote in this video. I hope seeing an example helps: https://youtu.be/2vXeJxYFou4
